---
- hosts: localhost
  gather_facts: no
  vars:
    vm_disk_location: /var/lib/libvirt/images
    image_location: /home/ece792/images/centos7_minimal.img
    root_pass: root
    vms:
      t2vm1:
        vm_name: t2vm1
        subnet_name: t2sub1
        vpc_name: t2vpc1
        os_type: centos7_minimal
        memory: 524 # in MBits
        vcpus: 2
        controller_network: controller_net

  tasks:
    - debug:
         msg: "{{vms}}"
    
    # Get List of VM Disks
    - name: Get list of VM disks
      command: "ls {{ vm_disk_location }}"
      register: disks
      changed_when: "disks.rc != 0"
      become: yes
  
    #Copy VM Disk Image for CentOS
    - name: Copy VM Disk Image for CentOS 7 Minimal
      copy:
        src: "{{dns_image_location}}"
        dest: "{{vm_disk_location}}/{{vms[item].vm_name}}.img"
      when: vms[item].vm_name not in disks.stdout
      with_items: "{{ vms | list }}"
      become: yes

    # List of VMs
    - name: Get list of VMs
      virt:
        command: "list_vms"
      register: vms

    #Define new vm
    - name: Define new vm
      virt:
        name: "{{dns_vms[item].dns_vm_name}}"
        command: define
        xml: "{{ lookup('template', 'templates/vm_template.xml.j2') }}"
      when: vms[item].dns_vm_name not in vms.list_vms
      with_items: "{{ vms | list }}"
      become: yes

    # Create and start new vm
    - name: Start vm
      virt:
        name: "{{dns_vms[item].dns_vm_name}}"
        command: create
      with_items: "{{ dns_vms | list }}"
      become: yes
    
