---
- hosts: localhost
  gather_facts: no
  vars:
    packages:
       - python-libvirt
       - python-lxml
    vm_disk_location: /var/lib/libvirt/images
    root_pass: root
  vars_files:
      - networks_vars.yml
      - guests_vars.yml

  tasks:
    - debug:
         msg: "{{networks}}"
    
    - debug:
         msg: "{{guests}}"
    # Install required packages
#    - name: Install required packages for libvirt, lxml
#      apt: 
#        name: "{{packages}}"
#      become: yes

    # Create an OVS type bridge
    - name: Create OVS Bridge
      openvswitch_bridge:
          bridge: "{{networks[item].bridge_name}}"
          state: present
      with_items: "{{ networks | list }}"
      ignore_errors: true
      become: yes

    # Set interface bridge up
    - name: Set Interface of bridges up
      command: "sudo ifconfig {{networks[item].bridge_name}} up"
      with_items: "{{ networks | list }}"
      ignore_errors: true
      become: yes
    
    # Define a new network
    - name: Define Virtual Network
      virt_net:
        command: define
        name: "{{networks[item].network_name}}"
        xml: "{{ lookup('template', 'templates/bridge_template.xml.j2' ) }}"
      with_items: "{{ networks | list }}"
      ignore_errors: true

    # Create and start a network
    - name: Create Virtual Network if not created
      virt_net:
        command: create
        name: "{{ networks[item].network_name }}"
      with_items: "{{ networks | list }}"
      ignore_errors: true
      become: yes